title: greg's bleg
email: gregory.danielson3@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Gregory's personal blog.
  If I find or think about something cool,
  I'll put it here so I don't forget about it.
  Here's hoping you find something cool here, too.
baseurl: ""  # TODO?
url: ""
show_excerpts: true
keywords: ["blog", "software", "music"]

# Build settings
theme: plainwhite-jekyll
remote_theme: thelehhman/plainwhite-jekyll
plugins:
  - jekyll-feed

plainwhite:
    name: Gregory Danielson
    tagline: Student, Developer @ UAB
    # sitemap: true
    date_format: "%b %-d, %Y"
    navigation:
        - title: My Work
          url: "/my-work"
        - title: My Resume
          url: "/resume"
    social_links:
        github: gregdan3
        gitlab: gregdan3
        linkedIn: in/gregdan3
        twitter: gregdan3d

owner:
    name: Gregory Danielson
    job: Software Developer & Teaching Assistant
    bio: TODO
    email: gregdan3@uab.edu
    github: gregdan3
    gitlab: gregdan3

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
